// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7ZUPq-SUZwX6uXzh1alPd6IuNmNe5g8',
    appId: '1:724483599798:web:31b58254f2f28d4ffaa517',
    messagingSenderId: '724483599798',
    projectId: 'personal-finance-manager-72016',
    authDomain: 'personal-finance-manager-72016.firebaseapp.com',
    storageBucket: 'personal-finance-manager-72016.firebasestorage.app',
    measurementId: 'G-BRZZ3MQ8HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsEVRHy03W9h1aN6-qPCDgmIwhhs2PXP4',
    appId: '1:724483599798:android:a18ff170a9b26945faa517',
    messagingSenderId: '724483599798',
    projectId: 'personal-finance-manager-72016',
    storageBucket: 'personal-finance-manager-72016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIV4ajzOh1ahlIMficEwUUTADTy470T3Y',
    appId: '1:724483599798:ios:3ca1291899d4017cfaa517',
    messagingSenderId: '724483599798',
    projectId: 'personal-finance-manager-72016',
    storageBucket: 'personal-finance-manager-72016.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIV4ajzOh1ahlIMficEwUUTADTy470T3Y',
    appId: '1:724483599798:ios:3ca1291899d4017cfaa517',
    messagingSenderId: '724483599798',
    projectId: 'personal-finance-manager-72016',
    storageBucket: 'personal-finance-manager-72016.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi7ZUPq-SUZwX6uXzh1alPd6IuNmNe5g8',
    appId: '1:724483599798:web:973c65d38b380fd0faa517',
    messagingSenderId: '724483599798',
    projectId: 'personal-finance-manager-72016',
    authDomain: 'personal-finance-manager-72016.firebaseapp.com',
    storageBucket: 'personal-finance-manager-72016.firebasestorage.app',
    measurementId: 'G-DK21WMCJRH',
  );
}
